[project]
name = "SandecoSendMessage"
version = "0.1.0"
description = "Envia Mensagem para WhatsApp usando EvolutionAPI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evolutionapi>=0.0.9",
    "flask>=3.1.0",
    "python-dotenv>=1.0.1",
    "streamlit>=1.41.1",
]
